---
deployment:
  tasks:
    # Set deployment path to /st1 subdirectory
    - export DEPLOYPATH=/home3/startech/public_html/st1/
    
    # Create directory if it doesn't exist
    - /bin/mkdir -p $DEPLOYPATH
    
    # Deploy all HTML files
    - /bin/cp *.html $DEPLOYPATH 2>/dev/null || true
    
    # Deploy .htaccess file
    - /bin/cp .htaccess $DEPLOYPATH 2>/dev/null || true
    
    # Deploy CSS directory
    - /bin/cp -R css $DEPLOYPATH
    
    # Deploy JS directory
    - /bin/cp -R js $DEPLOYPATH
    
    # Deploy images directory
    - /bin/cp -R images $DEPLOYPATH
    
    # Deploy vendor directory
    - /bin/cp -R vendor $DEPLOYPATH
    
    # Deploy backend directory
    - /bin/cp -R backend $DEPLOYPATH
