---
deployment:
  tasks:
    # Set deployment path to /st1 subdirectory
    - export DEPLOYPATH=/home3/startech/public_html/st1/
    
    # Create directory if it doesn't exist
    - /bin/mkdir -p $DEPLOYPATH
    
    # Deploy HTML files
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp index2.html $DEPLOYPATH
    - /bin/cp 404.html $DEPLOYPATH
    - /bin/cp about-us.html $DEPLOYPATH
    - /bin/cp cart.html $DEPLOYPATH
    - /bin/cp checkout.html $DEPLOYPATH
    - /bin/cp contact-us.html $DEPLOYPATH
    - /bin/cp product-full.html $DEPLOYPATH
    - /bin/cp product-sidebar.html $DEPLOYPATH
    - /bin/cp wishlist.html $DEPLOYPATH
    
    # Deploy CSS directory
    - /bin/cp -R css $DEPLOYPATH
    
    # Deploy JS directory
    - /bin/cp -R js $DEPLOYPATH
    
    # Deploy images directory
    - /bin/cp -R images $DEPLOYPATH
    
    # Deploy vendor directory
    - /bin/cp -R vendor $DEPLOYPATH
    
    # Deploy backend directory
    - /bin/cp -R backend $DEPLOYPATH
